version: '3.8'
services:
  netzfilm-db:
    container_name: pg_netzfilm
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netzfilm
    ports:
      - '5432:5432'
